### ISSUE TITLE
ssh and phing Issue

### ISSUE THREAD

**Issue by AlroneRhyn** [phingofficial/phing#1051]
Hello,

Since the update of those debian jessie packages (27th of march), the phing sshtask doesn't work any more (FileSyncTask is working though)

libssh2-1:amd64                    1.4.3-4.1+deb8u2
libssh2-1-dev:amd64                1.4.3-4.1+deb8u2

Phing 2.16.0

[PHP Error] ssh2_auth_pubkey_file(): Authentication failed for webadmin using public key: Unable to send userauth-publickey request [line 277 of /usr/share/php/phing/tasks/ext/ssh/SshTask.php]

Any Ideas ?

Thanks !

**Comment by mrook** [comment]
That doesn't sound like a Phing issue (especially if it used to work before). Could there be a problem with your public key, or something going on with the PHP ssh extension, or libssh? Perhaps you can search one of those projects for known issues.

**Comment by siad007** [comment]
@AlroneRhyn could you post your ssh2 pecl version?

**Comment by AlroneRhyn** [comment]
It doesn't work with ssh2-0.13-stable nor ssh2-0.12-beta.
Respectivly 5.6.33+dfsg-0+deb8u1 and 5.6.40+dfsg-0+deb8u1

**Comment by siad007** [comment]
It seems that there are problems using the pecl ssh2 package 0.x with a newer libssh2-1-dev version, as you allready mentioned. What you could do:

- [ ] roll back to the version where it works.
- [ ] add a bug report [@bugs.php.net](https://bugs.php.net/search.php?cmd=display&package_name[]=ssh2&direction=DESC&limit=30&status=Open)
- [ ] update your system to the last debian / php 7.x / phing 3.x / pecl ssh2 1.x for newer security fixes of libssh2

This issue is not phing related and will be closed.
