### ISSUE TITLE
get_magic_quotes_runtime() deprecated in 7.4 - replace HTTP_Request2

### ISSUE THREAD

**Issue by mrook** [phingofficial/phing#1160]
`HTTP_Request2`  still uses `get_magic_quotes_runtime()` and hasn't seen a real release since 2016. We should probably replace this package with something more modern & lightweight.

**Comment by kenguest** [comment]
Using a PSR18+PSR7 combo would probably be best. 

That way we are not tied to using one specific PSR7 library that we might have to later migrate from at a later date due to similar maintenance issues. 

With that in mind, I'd suggest implementing with HTTPlug ( http://httplug.io/ ) and perhaps Guzzle.
