### ISSUE TITLE
Phing 3 no longer completes runs that delete itself

### ISSUE THREAD

**Issue by linc** [phingofficial/phing#1891]
In v2, I would do this to the repo in which Phing was installed as a dev dependency:

```
    <!-- Run Composer, removing dev requirements. -->
    <target name="compose">
        <echo msg="Rebuilding Composer without dev files..." />
        <composer composer="/opt/homebrew/bin/composer" command="install">
            <arg value="--working-dir=${repo_root}" />
            <arg value="--no-dev" />
            <arg value="--optimize-autoloader" />
            <arg value="--quiet" />
        </composer>
    </target>
```

Subsequent steps would copy the `--no-dev` version of the project into a subfolder, then reinstall dev dependencies (including Phing itself).

The `copy` step now generates this error:

> BUILD FAILED
Class "Phing\Type\Reference" not found

This implies a new dependency on mid-flight file inclusions was added in v3.

If this is expected behavior / a silly edge case I happened to be exploiting in v2, fair enough, just thought I'd point out the non-parallel behavior not noted in the [upgrade guide](https://github.com/phingofficial/phing/blob/3.0.0/UPGRADING.md). I found it hugely convenient that it worked this way, since it vastly simplifies the build process to not need to clone the repo entirely or install Phing separately (making it a hidden setup step I need to document elsewhere).

**Comment by jawira** [comment]
Hello, it took me some time to understand the problem, so I'm writing this only to help Phing mantainers.

![image](https://github.com/user-attachments/assets/e6b50d18-96a2-40cd-b315-6ac6d106a36a)

1. You do `composer install`, therefore installing Phing and all other dev dependencies.
2. Then you execute Phing `vendor/bin/phing`. `main` is the default target, but `main` depends on `compose` target.
3. `compose` target is executed, and all dev dependencies are deleted, this means `vendor/phing` directory is also deleted.
4. `reset` target is executed
5. `copy` target is executed but an error raises. Class `Phing\Type\Reference` is required but cannot be loaded since `vendor/phing` directory no longer exists (see item 3 in this list).

As you mention this behavior is expected. One possible solution is to use the Phar version of Phing.  
Another possible solution is to first copy all files, and only then do a `compose --no-dev` within the copy dir (not the original dir where Phing resides).

Hope this helps.

**Comment by linc** [comment]
Sure, I can work around it, I'm just highlighting it was not the behavior Phing 2 had. This worked for its entire life, to my knowledge. I rolled back to 2.x for now until I have the patience to rethink it.

**Comment by mrook** [comment]
Hi @linc - the reason Phing 2 keeps working in your case is that all classes are loaded into memory at startup. Which means it doesn't matter that the actual file has been deleted. Since Phing 3 uses an autoloader, your issue becomes apparent.

It's not something we're going to change.

I'd rewrite your build process, you could copy your repository to a separate `build` directory and run a `--no-dev` install in that directory. Good luck!

**Comment by linc** [comment]
@mrook Makes sense, thanks for your work on Phing! We used it to distribute Vanilla Forums for 7 years (2015-2022), and I've now been using it to distribute [Nitro Porter](https://github.com/linc/nitro-porter) for the last 3. Probably gonna add it to another project in 2025.
