### ISSUE TITLE
Unwanted conversion value of Parameter from "true" to "1"

### ISSUE THREAD

**Issue by AKhrulev** [phingofficial/phing#660]
Tested on Phing 2.15.2
## Steps
Use parameter with value "true" in buildfile:
`<parameter type="SomeType" name="SomeName" value="true" />`
Get value of this parameter in code:
`$value = $parameter->getValue();`
## Expected result
$value is string "true"
## Actual result
$value is string "1"
## Notes
Value of parameter is automatically converted from "true" to "1". So it is **impossible** to have literally "true" in value (but this value is needed often, for example if we work with MS Visual Studio project files). I think that such conversion is useless because if we need value "1" then we just write value "1".

**Comment by mrook** [comment]
At this point, this is expected and intended behavior. We're looking at changing that, but I don't think feasible for 3.0 - it'll break a lot of build files.

If the documentation is lacking on this, then we need to address that.

**Comment by mrook** [comment]
Related: #539, #533, #534.

Thinking out loud: in 4.0 we could probably use reflection to find out the type of method arguments (assuming 4.0 will be PHP 7+) and only auto-convert strings for boolean arguments.

@mpdude what do you think?

**Comment by siad007** [comment]
@mrook we could extend the behavior by optionally adding a prefix to the value like:
`<parameter type="SomeType" name="SomeName" value="string:true" />` or `<parameter type="SomeType" name="SomeName" value="boolean:true" />` where the prefix part would be a class handling the transformation. As an addition this could be exchanged by own implementations like `<parameter type="SomeType" name="SomeName" value="namespace.custom.boolean:true" />`

**Comment by mpdude** [comment]
IIRC I have worked on this (or a similar?) issue many years ago. Also see http://phing.tigris.org/ds/viewMessage.do?dsForumId=1079&dsMessageId=2771568.

If memory serves me correctly, the problem was that conversion of strings like "f", "true" etc. to boolean values happens somewhere in the code that is responsible for wiring up/configuring tasks. At that place, however, you cannot tell whether a boolean value or a string is required. Only tasks themselves can tell what they expect their arguments to be.

I came up with this helper class: https://github.com/phingofficial/phing/blob/unstable-3.0/classes/phing/util/Boolean.php

That way, the configuration/generic build file handling just leaves strings as-is, and all tasks need to be updated to call `Boolean::cast(...)` in their setters when they expect boolean flags.

Additionally, we could allow `haveXXX()` methods instead of `setXXX()` setters. That method name could be a hint for the "wiring" code to perform the boolean conversion before passing values to the task.

**Comment by mrook** [comment]
Booleans are interpreted in `IntrospectionHelper`.

**Comment by mpdude** [comment]
@mrook Where exactly are you expecting build file breakage in 3.0, and why is a 3.0 not a good point to fix this?

**Comment by mrook** [comment]
@mpdude pretty much every build file that relies on `true` being mapped to `1`, right? The timing of the 3.0 release is one reason.

**Comment by mpdude** [comment]
Well, if we update all (included/out of the box) `Task`s to apply that `Boolean::cast()`, they would continue to work as previously with values like `true`, `1`, `t`, ... At the same time, we would fix that you cannot, for example, use `f` as a property name or that `foo = true` in a properties file does not behave the same as `<property name="foo" value="true" />`.

A major version increment is the only time we can make such changes and put a big notice in the upgrading log. 

For the same reasons, we should have major version increments really sparingly as they are complex for users to handle and take time. So IMO if this is a bug we'd want to have fixed this should be in `3.0`, possibly deferring the release. Please let us not talk about a `4.0` already now :-(.
